name: Build book

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build book for screen
        run: pnpm run build

      - name: build book for print
        run: pnpm run build:print

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-pdfs
          path: ./*.pdf
          if-no-files-found: error
          retention-days: 3